# Generated by Django 3.1.4 on 2021-05-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
