# Generated by Django 3.1.4 on 2021-05-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210526_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmt',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
