# Generated by Django 3.2.4 on 2021-06-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_modernblogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='modernblogs',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='modernblogs',
            name='point1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='modernblogs',
            name='point2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='modernblogs',
            name='point3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='modernblogs',
            name='point4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='modernblogs',
            name='point5',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='modernblogs',
            name='point6',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='modernblogs',
            name='point7',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='modernblogs',
            name='desc1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='modernblogs',
            name='desc2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='modernblogs',
            name='desc3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='modernblogs',
            name='desc4',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='modernblogs',
            name='desc5',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='modernblogs',
            name='desc6',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='modernblogs',
            name='desc7',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='modernblogs',
            name='img1',
            field=models.ImageField(default='', upload_to='blogImages'),
        ),
        migrations.AlterField(
            model_name='modernblogs',
            name='img2',
            field=models.ImageField(default='', upload_to='blogImages'),
        ),
        migrations.AlterField(
            model_name='modernblogs',
            name='img3',
            field=models.ImageField(default='', upload_to='blogImages'),
        ),
        migrations.AlterField(
            model_name='modernblogs',
            name='img4',
            field=models.ImageField(default='', upload_to='blogImages'),
        ),
        migrations.AlterField(
            model_name='modernblogs',
            name='img5',
            field=models.ImageField(default='', upload_to='blogImages'),
        ),
        migrations.AlterField(
            model_name='modernblogs',
            name='img6',
            field=models.ImageField(default='', upload_to='blogImages'),
        ),
        migrations.AlterField(
            model_name='modernblogs',
            name='img7',
            field=models.ImageField(default='', upload_to='blogImages'),
        ),
    ]
