# Generated by Django 3.0.5 on 2021-06-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210614_2337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
