# Generated by Django 3.0.5 on 2021-06-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='modernblogs',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
