# Generated by Django 3.0.5 on 2021-06-15 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_userip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='blog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.ModernBlogs'),
        ),
    ]
