# Generated by Django 3.0.5 on 2021-06-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_userip_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='modernblogs',
            name='publist_status',
            field=models.CharField(choices=[('p', 'Public'), ('r', 'Private')], default='', max_length=50),
        ),
    ]
