# Generated by Django 3.0.5 on 2021-06-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_modernblogs_publist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='modernblogs',
            name='tag',
            field=models.CharField(default='', max_length=15),
        ),
    ]
